events {
    worker_connections 1024;
}

http {
    upstream identity_service {
        server identityservice:8080;
    }

    upstream event_service {
        server eventcatalogservice:8080;
    }

    upstream follower_service {
        server followerservice:8080;
    }

    upstream blazor_app {
        server blazorapp:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://blazor_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /api/identity {
            proxy_pass http://identity_service;
            proxy_set_header Host $host;
        }

        location /api/events {
            proxy_pass http://event_service;
            proxy_set_header Host $host;
        }

        location /api/follower {
            proxy_pass http://follower_service;
            proxy_set_header Host $host;
        }
    }
}
